// 使用需要 cdnUrl + mask[0]
// 上传前缀 `MPTian/{mask}/`
const imgList = {
    mask: [
        '/MPTian/mask/0.png',
        '/MPTian/mask/1.png',
        '/MPTian/mask/2.png',
        '/MPTian/mask/3.png',
        '/MPTian/mask/4.png',
        '/MPTian/mask/5.png',
        '/MPTian/mask/6.png',
        '/MPTian/mask/7.png',
        '/MPTian/mask/8.png',
        '/MPTian/mask/9.png',
        '/MPTian/mask/10.png',
        '/MPTian/mask/11.png',
        '/MPTian/mask/12.png',
        '/MPTian/mask/13.png',
        '/MPTian/mask/14.png',
        '/MPTian/mask/15.png',
        '/MPTian/mask/16.png',
        '/MPTian/mask/17.png',
        '/MPTian/mask/18.png',
        '/MPTian/mask/19.png',
        '/MPTian/mask/20.png',
        '/MPTian/mask/21.png',
        '/MPTian/mask/22.png',
        '/MPTian/mask/23.png',
        '/MPTian/mask/24.png',
        '/MPTian/mask/25.png',
        '/MPTian/mask/26.png',
        '/MPTian/mask/27.png',
        '/MPTian/mask/28.png',
    ],
    yuandan: [],
    qingren: [],
    nvshen: [],
    qingming: [],
    laodong: [],
    ertong: [],
    gaokao: [

    ],
    jiandang: [],
    jianjun: [],
    jiaoshi: [],
    guoqing: [],
    shengdan: [
        '/MPTian/shengdan/0.png',
        '/MPTian/shengdan/1.png',
        '/MPTian/shengdan/2.png',
        '/MPTian/shengdan/3.png',
        '/MPTian/shengdan/4.png',
        '/MPTian/shengdan/5.png',
        '/MPTian/shengdan/6.png',
        '/MPTian/shengdan/7.png',
        '/MPTian/shengdan/8.png',
        '/MPTian/shengdan/9.png',
    ],
    chunjie: [],
    yuanxiao: [],
    duanwu: [
        '/MPTian/duanwu/0.png',
        '/MPTian/duanwu/1.png',
        '/MPTian/duanwu/2.png',
        '/MPTian/duanwu/3.png',
        '/MPTian/duanwu/4.png',
        '/MPTian/duanwu/5.png',
        '/MPTian/duanwu/6.png',
        '/MPTian/duanwu/7.png',
        '/MPTian/duanwu/8.png',
        '/MPTian/duanwu/9.png',
        '/MPTian/duanwu/0.png',
        '/MPTian/duanwu/11.png',
        '/MPTian/duanwu/12.png',
        '/MPTian/duanwu/13.png',
        '/MPTian/duanwu/14.png',
    ],
    qixi: [
        '/MPTian/qixi/0.png',
        // '/MPTian/qixi/1.png',
        '/MPTian/qixi/2.png',
        '/MPTian/qixi/3.png',
        '/MPTian/qixi/4.png',
        '/MPTian/qixi/5.png',
        '/MPTian/qixi/6.png',
        '/MPTian/qixi/7.png',
        '/MPTian/qixi/8.png',
        '/MPTian/qixi/9.png',
        '/MPTian/qixi/0.png',
        '/MPTian/qixi/11.png',
        '/MPTian/qixi/12.png',
        '/MPTian/qixi/13.png',
        '/MPTian/qixi/14.png',
        '/MPTian/qixi/15.png',
        '/MPTian/qixi/16.png',
    ],
    zhongqiu: [],
    muqinjie: [
        '/MPTian/muqinjie/0.png',
        '/MPTian/muqinjie/1.png',
        '/MPTian/muqinjie/2.png',
        '/MPTian/muqinjie/3.png',
        '/MPTian/muqinjie/4.png',
        '/MPTian/muqinjie/5.png',
        '/MPTian/muqinjie/6.png',
        '/MPTian/muqinjie/7.png',
        '/MPTian/muqinjie/8.png',
        '/MPTian/muqinjie/9.png',
        '/MPTian/muqinjie/10.png',
        '/MPTian/muqinjie/11.png',
        '/MPTian/muqinjie/12.png',
        '/MPTian/muqinjie/13.png',
        '/MPTian/muqinjie/14.png',
        '/MPTian/muqinjie/15.png',
        '/MPTian/muqinjie/16.png',
        '/MPTian/muqinjie/17.png',
        '/MPTian/muqinjie/18.png',
    ],
    fuqinjie: [
        '/MPTian/fuqinjie/0.png',
        '/MPTian/fuqinjie/1.png',
        '/MPTian/fuqinjie/2.png',
        '/MPTian/fuqinjie/3.png',
        '/MPTian/fuqinjie/4.png',
        '/MPTian/fuqinjie/5.png',
        '/MPTian/fuqinjie/6.png',
        '/MPTian/fuqinjie/7.png',
        '/MPTian/fuqinjie/8.png',
        '/MPTian/fuqinjie/9.png',
        '/MPTian/fuqinjie/10.png',
        '/MPTian/fuqinjie/11.png',
        '/MPTian/fuqinjie/12.png',
        '/MPTian/fuqinjie/13.png',
        '/MPTian/fuqinjie/14.png',
        '/MPTian/fuqinjie/15.png',
        '/MPTian/fuqinjie/16.png',
        '/MPTian/fuqinjie/17.png',
        '/MPTian/fuqinjie/18.png',
        '/MPTian/fuqinjie/19.png',
        '/MPTian/fuqinjie/20.png',
        '/MPTian/fuqinjie/21.png',
        '/MPTian/fuqinjie/22.png',
        '/MPTian/fuqinjie/23.png',
    ],
}

export default imgList