// 使用需要 cdnUrl + mask[0]
// 上传前缀 `MPTian/{mask}/`
const imgList = {
    mask: [
        '/MPTian/mask/0.png',
        '/MPTian/mask/1.png',
        '/MPTian/mask/2.png',
        '/MPTian/mask/3.png',
        '/MPTian/mask/4.png',
        '/MPTian/mask/5.png',
        '/MPTian/mask/6.png',
        '/MPTian/mask/7.png',
        '/MPTian/mask/8.png',
        '/MPTian/mask/9.png',
        '/MPTian/mask/10.png',
        '/MPTian/mask/11.png',
        '/MPTian/mask/12.png',
        '/MPTian/mask/13.png',
        '/MPTian/mask/14.png',
        '/MPTian/mask/15.png',
        '/MPTian/mask/16.png',
        '/MPTian/mask/17.png',
        '/MPTian/mask/18.png',
        '/MPTian/mask/19.png',
        '/MPTian/mask/20.png',
        '/MPTian/mask/21.png',
        '/MPTian/mask/22.png',
        '/MPTian/mask/23.png',
        '/MPTian/mask/24.png',
        '/MPTian/mask/25.png',
        '/MPTian/mask/26.png',
        '/MPTian/mask/27.png',
        '/MPTian/mask/28.png',
    ],
    yuandan: [],
    qingren: [],
    nvshen: [],
    qingming: [],
    laodong: [],
    ertong: [],
    gaokao: [

    ],
    jiandang: [],
    jianjun: [],
    jiaoshi: [],
    guoqing: [],
    shengdan: [
        '/MPTian/shengdan/0.png',
        '/MPTian/shengdan/1.png',
        '/MPTian/shengdan/2.png',
        '/MPTian/shengdan/3.png',
        '/MPTian/shengdan/4.png',
        '/MPTian/shengdan/5.png',
        '/MPTian/shengdan/6.png',
        '/MPTian/shengdan/7.png',
        '/MPTian/shengdan/8.png',
        '/MPTian/shengdan/9.png',
    ],
    chunjie: [],
    yuanxiao: [],
    duanwu: [],
    qixi: [
        '/MPTian/qixi/0.png',
        // '/MPTian/qixi/1.png',
        '/MPTian/qixi/2.png',
        '/MPTian/qixi/3.png',
        '/MPTian/qixi/4.png',
        '/MPTian/qixi/5.png',
        '/MPTian/qixi/6.png',
        '/MPTian/qixi/7.png',
        '/MPTian/qixi/8.png',
        '/MPTian/qixi/9.png',
        '/MPTian/qixi/0.png',
        '/MPTian/qixi/11.png',
        '/MPTian/qixi/12.png',
        '/MPTian/qixi/13.png',
        '/MPTian/qixi/14.png',
        '/MPTian/qixi/15.png',
        '/MPTian/qixi/16.png',
    ],
    zhongqiu: [],
    muqinjie: [],
    fuqinjie: [],
}

export default imgList